# Generated by Django 2.2 on 2022-02-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_captioning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='captionreview',
            name='caption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_captioning.Caption'),
        ),
        migrations.AlterField(
            model_name='captionreview',
            name='rate',
            field=models.CharField(choices=[('VL', 'Very Lo2'), ('LO', 'Low'), ('OK', 'Ok'), ('GO', 'Good'), ('VG', 'Very Good')], default='OK', max_length=2),
        ),
    ]
