# Generated by Django 2.2 on 2022-02-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_captioning', '0002_auto_20220221_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionreview',
            name='rate',
            field=models.CharField(choices=[('VL', 'Very Low'), ('LO', 'Low'), ('OK', 'Ok'), ('GO', 'Good'), ('VG', 'Very Good')], default='OK', max_length=2),
        ),
    ]
