# Generated by Django 2.2 on 2022-02-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_captioning', '0003_auto_20220221_1924'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='caption',
            table='caption_predictions',
        ),
        migrations.AlterModelTable(
            name='captionreview',
            table='caption_reviews',
        ),
    ]
