# Generated by Django 2.2 on 2022-02-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_captioning', '0006_auto_20220222_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionreview',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
